//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryWidget.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryWidget.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }

        public static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }

        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }

        public static string HealthCold {
            get {
                return ResourceManager.GetString("HealthCold", resourceCulture);
            }
        }

        public static string HealthDead {
            get {
                return ResourceManager.GetString("HealthDead", resourceCulture);
            }
        }

        public static string HealthGood {
            get {
                return ResourceManager.GetString("HealthGood", resourceCulture);
            }
        }

        public static string HealthOverheat {
            get {
                return ResourceManager.GetString("HealthOverheat", resourceCulture);
            }
        }

        public static string HealthOverVoltage {
            get {
                return ResourceManager.GetString("HealthOverVoltage", resourceCulture);
            }
        }

        public static string HealthUnknown {
            get {
                return ResourceManager.GetString("HealthUnknown", resourceCulture);
            }
        }

        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        public static string NotificationChannelDescription {
            get {
                return ResourceManager.GetString("NotificationChannelDescription", resourceCulture);
            }
        }

        public static string NotificationChannelName {
            get {
                return ResourceManager.GetString("NotificationChannelName", resourceCulture);
            }
        }

        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }

        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }

        public static string PowerSave {
            get {
                return ResourceManager.GetString("PowerSave", resourceCulture);
            }
        }

        public static string PowerSaveShort {
            get {
                return ResourceManager.GetString("PowerSaveShort", resourceCulture);
            }
        }

        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        public static string StatusCharging {
            get {
                return ResourceManager.GetString("StatusCharging", resourceCulture);
            }
        }

        public static string StatusDischarging {
            get {
                return ResourceManager.GetString("StatusDischarging", resourceCulture);
            }
        }

        public static string StatusFull {
            get {
                return ResourceManager.GetString("StatusFull", resourceCulture);
            }
        }

        public static string StatusNotCharging {
            get {
                return ResourceManager.GetString("StatusNotCharging", resourceCulture);
            }
        }

        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }

        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }

        public static string TemperatureUnit {
            get {
                return ResourceManager.GetString("TemperatureUnit", resourceCulture);
            }
        }

        public static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }

        public static string WidgetInstructions {
            get {
                return ResourceManager.GetString("WidgetInstructions", resourceCulture);
            }
        }

        public static string WidgetLabelHealth {
            get {
                return ResourceManager.GetString("WidgetLabelHealth", resourceCulture);
            }
        }

        public static string WidgetLabelStatus {
            get {
                return ResourceManager.GetString("WidgetLabelStatus", resourceCulture);
            }
        }

        public static string WidgetLabelTemp {
            get {
                return ResourceManager.GetString("WidgetLabelTemp", resourceCulture);
            }
        }
    }
}
